services:
  - type: web
    name: valecondos-front-portaria
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://vale-acesso-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
